[package]
name = "benchmarks"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
areion = { path = ".." }
blake3 = "1.5.0"
divan = "0.1.2"
sha2 = { version = "0.10.6", default-features = false, features = ["asm"] }

[[bench]]
name = "benchmarks"
harness = false
